import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Providers } from "@/components/providers";
import { NextAuthProvider } from "@/app/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* React query provider: */}
        {/*<NextAuthProvider>*/}
        <Providers>{children}</Providers>
        {/*</NextAuthProvider>*/}
      </body>
    </html>
  );
}
